config/routes.rb
Rails.application.routes.draw do

  	devise_for :admins , controllers: { registrations: 'registration'}


	root to: "home#index"
	#Edit
	get 'home/edit' , to: 'home#edit', as: 'edit_home'
	patch 'home', to: 'home#update'


	# Landmarks
	get 'curricula' , to: 'curricula#view'			# Tutti i curriculum
	get 'courses' , to: 'courses#view'				# Tutti i corsi
	get 'services' , to: 'services#view'			# Tutti i servizi
	get 'services/type/:id/' , to: 'services#type'		# Servizi per tipo
	get 'contacts' , to: 'contacts#view', as: 'contact'			# Contatti
	get 'mission' , to: 'mission#view', as: 'mission'				# Mission & Principles
	get 'how_to_get_there' , to: 'how_to_get_there#view', as: 'how_to_get_there'	# Come arrivare
	get 'structures' , to: 'structures#view', as: 'structures'	# Tutte le strutture
	get 'structures/type/:id/' , to: 'structures#type'		# Strutture per tipo
	get 'events' , to: 'events#view'				# Tutti gli eventi
	post 'events/bydate' , to: 'events#bydate'			# Eventi per data
	get 'events/type/:id/' , to: 'events#type'			# Eventi per tipo
	get 'awards' , to: 'awards#view'				# Tutti i riconoscimenti
	get 'history', to: 'history#view', as: 'history'
	get 'alumni', to: 'alumni#view'


	#bureaucracy
	get 'bureaucracy' , to: 'bureaucracy#view', as: 'bureaucracy'	# Burocrazia
	get 'regulation' , to: 'regulation#view',as: 'regulation'	# Regolamento
	get 'costs' , to: 'costs#view', as: 'cost'	# Costi
	get 'bursary' , to: 'bursary#view', as: 'bursary'	# Borse di studio
	#Edit
	get 'bureaucracy/edit' , to: 'bureaucracy#edit', as: 'edit_bureaucracy'
	patch 'bureaucracy', to: 'bureaucracy#update'

	get 'regulation/edit' , to: 'regulation#edit', as: 'edit_regulation'
	patch 'regulation' , to: 'regulation#update'

	get 'costs/edit' , to: 'costs#edit', as: 'edit_cost'
	patch 'costs' , to: 'costs#update'

	get 'bursary/edit' , to: 'bursary#edit', as: 'edit_bursary'
	patch 'bursary' , to: 'bursary#update'

	#Edit for single topic

	get 'mission/edit' , to: 'mission#edit', as: 'edit_mission'
	patch 'mission', to: 'mission#update'

	get 'history/edit' , to: 'history#edit', as: 'edit_history'
	patch 'history', to: 'history#update'

	get 'awards/edit' , to: 'awards#edit', as: 'edit_awards'
	patch 'awards', to: 'awards#update'

	get 'how_to_get_there/edit' , to: 'how_to_get_there#edit', as: 'edit_how_to_get_there'
	patch 'how_to_get_there', to: 'how_to_get_there#update'

	get 'contacts/edit' , to: 'contacts#edit', as: 'edit_contacts'
	patch 'contacts', to: 'contacts#update'

	# CRUD Course pages
	get 'courses/index', to: 'course#index', as: 'course_index'
	get 'courses/new', to: 'course#new', as: 'new_course'
	post 'courses', to: 'course#create'
	get 'course/:id', to: 'course#view', as: 'course'
	get 'course/:id/edit', to: 'course#edit', as: 'course_edit'
	put 'course/:id', to: 'course#update'
	delete 'course/:id', to: 'course#destroy'



	#Courses page
	get 'course/:id/syllabus' , to: 'course#syllabus', as: 'course_syllabus'
	get 'course/:id/timetable' , to: 'course#timetable', as: 'course_timetable'
	get 'course/:id/materials' , to: 'course#materials', as: 'course_materials'
	get 'course/:id/exams' , to: 'course#exams', as: 'course_exams'
	get 'course/:id/curricula' , to: 'course#curricula', as: 'course_curricula'

	#Dirty way for gt!
	get 'courses/courses_by_type/:curriculum_id/:id/syllabus' , to: 'course#syllabus', as: 'courses_type_guided_tour_id_syllabus'
	get 'courses/courses_by_year/:courses_year/:id/syllabus' , to: 'course#syllabus', as: 'courses_year_guided_tour_id_syllabus'
	get 'courses/courses_by_type/:curriculum_id/:id/timetable' , to: 'course#timetable', as: 'courses_type_guided_tour_id_timetable'
	get 'courses/courses_by_year/:courses_year/:id/timetable' , to: 'course#timetable', as: 'courses_year_guided_tour_id_timetable'




	#CRUD courses news
	get 'course/:course_id/news/index' , to: 'news#index', as: 'course_news_index'
	get 'course/:course_id/news/new' , to: 'news#new', as: 'new_course_news'
	post 'course/:course_id/news' , to: 'news#create'
	get 'course/:course_id/news/:id/edit' , to: 'news#edit', as: 'edit_course_new'
	put 'course/:course_id/news/:id' , to: 'news#update'
	delete 'course/:course_id/news/:id' , to: 'news#destroy'
	# News pages
	get 'course/:course_id/news/:id' , to: 'news#view', as: 'course_new'


	#Courses news
	get 'course/:id/news' , to: 'news#news', as: 'course_news'
	delete 'course/:course_id/news/:id' , to: 'news#destroy'

	#Lecture CRUD
	get 'course/:course_id/lectures/index' , to: 'lectures#index', as: 'course_lectures_index'
	get 'course/:course_id/lectures/new' , to: 'lectures#new', as: 'new_course_lecture'
	post 'course/:course_id/lectures' , to: 'lectures#create'
	get  'course/:course_id/lectures/:id/edit' , to: 'lectures#edit', as: 'edit_course_lecture'
	put  'course/:course_id/lectures/:id' , to: 'lectures#update', as: 'update_course_lecture'
	delete 'course/:course_id/lectures/:id' , to: 'lectures#destroy'

	#lecture pages
	get 'course/:course_id/lectures/:id' , to: 'lectures#show', as: 'course_lecture'

	#courses pages
	get 'courses/courses_by_year' , to: 'course#courses_by_year', as: 'courses_by_year'
	get 'courses/courses_by_type' , to: 'course#courses_by_type', as: 'courses_by_type'
	post 'courses/courses_by_year' , to: 'course#courses_by_year'
	post 'courses/courses_by_type' , to: 'course#courses_by_type'
	get 'courses/courses_by_type/:id' , to: 'course#type_guided_tour', as: 'courses_type_guided_tour'
	get 'courses/courses_by_year/:id' , to: 'course#year_guided_tour', as: 'courses_year_guided_tour'
	get 'courses/courses_by_type/:curriculum_id/:id' , to: 'course#type_guided_tour', as: 'courses_type_guided_tour_id'
	get 'courses/courses_by_year/:courses_year/:id' , to: 'course#year_guided_tour', as: 'courses_year_guided_tour_id'


	# Teacher pages
  get 'teacher/index' , to: 'teacher#index', as: 'teacher_index'
	get 'teacher/new' , to: 'teacher#new', as: 'new_teacher'
	get 'teacher/:id' , to: 'teacher#view', as: 'teacher'
	get 'teacher/:id/curriculum' , to: 'teacher#curriculum', as: 'teacher_curriculum'

	#CRUD teacher

	post 'teacher' , to: 'teacher#create'
	get 'teacher/:id/edit' , to: 'teacher#edit', as: 'edit_teacher'
	put 'teacher/:id' , to: 'teacher#update'
	delete 'teacher/:id' , to: 'teacher#destroy'

	# Curriculum new, edit, and destoy
	get 'curriculum/index' , to: 'curriculum#index', as: 'curriculum_index'
	get 'curriculum/new' , to: 'curriculum#new', as: 'new_curriculum'
	get 'curriculum/:curriculum_id/courses/index', to: 'curriculum#manage_courses', as: 'curriculum_courses'
	get 'curriculum/:curriculum_id/courses/list', to: 'curriculum#list_courses_to_add', as: 'list_curriculum_courses'
	put 'curriculum/:curriculum_id/courses/:id', to: 'curriculum#add_course', as: 'add_curriculum_course'
	delete 'curriculum/:curriculum_id/courses/:id', to: 'curriculum#remove_course'
	post 'curriculum' , to: 'curriculum#create'
	get 'curriculum/:id/edit' , to: 'curriculum#edit', as: 'edit_curriculum'
	put 'curriculum/:id' , to: 'curriculum#update'
	delete 'curriculum/:id' , to: 'curriculum#destroy'

	# Curriculum pages
	get 'curriculum/:id' , to: 'curriculum#view', as: 'curriculum_id'
	get 'curriculum/:id/work_opportunity' , to: 'curriculum#work_opportunity', as: 'curriculum_work_opportunity'



	#CRUD Material
	get 'course/:course_id/material/index' , to: 'material#index', as: 'course_material_index'
	get 'course/:course_id/material/new' , to: 'material#new', as: 'new_course_material'
	post 'course/:course_id/material' , to: 'material#create'
	get  'course/:course_id/material/:id/edit' , to: 'material#edit', as: 'edit_course_material'
	put  'course/:course_id/material/:id' , to: 'material#update', as: 'update_course_material'
	delete 'course/:course_id/material/:id' , to: 'material#destroy'
	# Material pages
	get 'course/:course_id/material/:id' , to: 'material#view', as: 'material'

	# Exams pages
  	get 'exam/index' , to: 'exam#index', as: 'exam_index'
	get 'exam/new' , to: 'exam#new', as: 'new_exam'
	get 'exam/:id' , to: 'exam#view', as: 'exam'

	# CRUD exam

	post 'exam' , to: 'exam#create'
	get 'exam/:id/edit' , to: 'exam#edit', as: 'edit_exam'
	put 'exam/:id' , to: 'exam#update'
	delete 'exam/:id' , to: 'exam#destroy'

	# Classrooms pages
	get 'classroom/new' , to: 'classroom#new', as: 'new_classroom'
  get 'classroom/index', to: 'classroom#index', as: 'classroom_index'
	get 'classroom/:id' , to: 'classroom#view' , as: 'classroom'
	get 'classroom/:id/how_to_get_there' , to: 'classroom#how_to_get_there', as: "classroom_htgt"
	get 'classroom/:id/services', to: 'classroom#services', as: 'classroom_services'
	get 'classroom/:id/exams', to: 'classroom#exams', as: 'classroom_exams'
	get 'classroom/:id/courses', to: 'classroom#courses', as: 'classroom_courses'

	#CRUD classroom

	post 'classroom' , to: 'classroom#create'
	get 'classroom/:id/edit' , to: 'classroom#edit', as: 'edit_classroom'
	put 'classroom/:id' , to: 'classroom#update'
	delete 'classroom/:id' , to: 'classroom#destroy'

	# Student's services pages
	get 'service/index' , to: 'service#index', as: 'service_index'
	get 'service/:id' , to: 'service#view', as: 'service'
	get 'service/:id/reference' , to: 'service#reference', as: 'service_reference'
	# CRUD services
	get 'services/new' , to: 'service#new', as: 'new_service'
	post 'service' , to: 'service#create'
	get 'service/:id/edit' , to: 'service#edit', as: 'edit_service'
	put 'service/:id' , to: 'service#update'
	delete 'service/:id' , to: 'service#destroy'

	# Structures pages
	get 'structure/index', to: 'structure#index', as: 'structure_index'
	get 'structure/:id' , to: 'structure#view', as: 'structure'
	get 'structure/:id/map' , to: 'structure#map', as: 'structure_map'
	get 'structure/:id/photogallery' , to: 'structure#photogallery', as: 'structure_photos'
	get 'structure/:id/events' , to: 'structure#events', as: 'structure_events'
	get 'structure/:id/services' , to: 'structure#services', as: 'structure_services'
	#CRUD structures

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :teacher, inverse_of:  :course
  has_and_belongs_to_many  :curriculum 
  has_many :material, inverse_of:  :course
  has_many :exam, inverse_of:  :course
  has_one :classroom, inverse_of:  :course
  has_many :news, inverse_of:  :course
  has_many :lecture


  #validation
  validates :name, :description, :program, :teacher_id, :classroom_id, :accademic_year, presence: true
  validates :name, length: {in: 6...50}
  validates :description, length: {minimum: 20}
  validates :program , length: {minimum: 20}
  validates :teacher_id, numericality: { only_integer: true }


  self.per_page = 4
  def self.max_word 
   15
  end
end

app/helpers/course_helper.rb
module CourseHelper
end

app/views/course/_course_form.html.erb
<%= form_for what, url:{ controller: 'course', action: to_do}, method: to_met do |f| %>

	<p><%= f.label :name %> <br/>
		<%= f.text_field :name %> 
	</p>
	<p><%= f.label :description%> <br/>
		<%= f.text_area :description %>
	</p>
	<p><%= f.label :program %> <br/>
		<%= f.text_area :program%> 
	</p>
	<p><%= f.label :teacher %> <br/>
		<%= f.select :teacher_id, Teacher.order('lastname ASC').map{|t| [ "#{t.lastname} #{t.firstname}",t.id] }  %> 
	</p>
	<p><%= f.label :classroom %> <br/>
		<%= f.collection_select :classroom_id, Classroom.order('name ASC'),:id, :name %> 
	</p>
	<p>
		<%= f.label :curriculum %> <br/>
		<%= f.label :curriculum_message, "Remember to add the course to a curriculum in the curriculum managment page" %>
	</p>
	<p><%= f.label :start_time %> <br/>
		<%= f.date_select :accademic_year, order: [:day, :month, :year] %>
	</p>

	<br><%= f.submit %>
	<% end %>

app/views/course/_course_table.html.erb
<table class="styled-table" >
	<thead>
		<th>Course Name	</th>
		<th>Professor</th>
		
		<th>Description</th>
	</tr>
	</thead>
	<tbody>
		<% @courses.each do |c| %>
			<tr>
		
			<td><%= link_to c.name, "#{:go_to}#{c.id}" %></td>
			<td><%= link_to "#{c.teacher.firstname} #{c.teacher.lastname}", teacher_path(c.teacher.id) %></td>
			<td><%= link_to "#{c.description.split[0...Course.max_word].join(' ')} ...",course_syllabus_path(c.id)  %></td>


			</tr>
		<% end %>
	</tbody>

</table>

<%= page_entries_info @courses %>
<%= will_paginate @courses %>

app/views/course/_show.html.erb
	<!-- if is not defined a special name of the course to use as a title -->
	<!-- use the course name -->
	<% name ||= course.name %>
	<%= title name %>
	<%= course.description.html_safe %>

app/views/course/courses_by_type.html.erb
 
<%= title "Courses for curriculum #{@curriculum.name}" %>

<table class="styled-table" >
	<thead>
		<th>Course Name	</th>
		<th>Professor</th>
		
		<th>Description</th>
	</tr>
	</thead>
	<tbody>
		<% @courses.each do |course| %>
			<tr>
		
			<td><%= link_to course.name, courses_type_guided_tour_id_path(@curriculum, course) %></td>
			<td><%= "#{course.teacher.firstname} #{course.teacher.lastname}"%></td>
			<td><%= "#{course.description.split[0...Course.max_word].join(' ')} ..."%></td>


			</tr>
		<% end %>
	</tbody>

</table>




<%= render 'shared/hide_structural_link' %>
<%= render 'shared/hide_semantic_link' %>

app/views/course/courses_by_year.html.erb
<%= title "Courses in the year #{@year}" %>

<%= render "shared/hide_semantic_link" %>
<%= render "shared/hide_structural_link" %>

<table class="styled-table" >
	<thead>
		<th>Course Name	</th>
		<th>Description</th>
		<th>Professor</th>
		<th>Curricula</th>
		
	</tr>
	</thead>
	<tbody>

	<tr>
	
	<% @courses.each do |course| %>
		<tr>
			<td class="name"><%= link_to course[:name], courses_year_guided_tour_id_path(@year,course[:id]) %>	</td>
			<td class="description"><%= "#{course[:description].split[0...Course.max_word].join(' ')} ..." %></td>
			</td>
			<td class="teacher"><%= course[:teacher] %></td>
			<td class ="curricula">
			
			<% course[:curricula].each do |curriculum| %>
				<%= curriculum[:name] %>
				<br> <%# usato per mettere ogni elemento su una buona linea %>
				
			<% end %>
			
			
			

		</tr>
	<% end %>


</tbody>


</table>
<br>



<%= will_paginate @courses_by_year %>

app/views/course/curricula.html.erb
<%= title @name %>

<%= render 'shared/curriculum_table' %>


<%= render "shared/hide_structural_link" %>
<%= render "shared/semantic_link" %>

app/views/course/edit.html.erb
<%= title "Edit Course #{@course.name}" %>

<%= render partial:'shared/error_partial', locals:{what: @course, name:'course'} %>
<%= render partial:'course_form', locals: {to_do:'update' , to_met: 'put', what: @course} %>

app/views/course/exams.html.erb
<%= title "Exams for #{@name}" %>

<ul>
<table class="styled-table" >
	<thead>
		<tr>
			<th>Name </th>
			<th>Description</th>
			<th>Classroom</th>
			<th>Date</th>

		</tr>

	</thead>
	<tbody>

		<% @exams.each do |exam| %>
			<tr>
				<td><%= link_to exam.name, exam_path(exam) %></td>
				<td><%= exam.description %></td>
				<td><%= link_to exam.classroom.name, classroom_path(exam.classroom) %></td>
				<td><%= exam.time.strftime("%A,%d/%m/%Y - %R") %></td>
			</tr>

		<% end %>

	</tbody>


</table>

<%= render 'shared/semantic_link' %>
<%= render 'shared/hide_structural_link' %>

app/views/course/index.html.erb
<%= title "Listing Courses" %>

<%= link_to "New Course", new_course_path, {class: "new_button"} %>

<br><br>

<table class="styled-table" >
	<thead>
		<tr>
			<th>Name </th>
			<th>Description</th>
			<th>Professor</th>
			<th>Curricula</th>
			<th>Year</th>
			<th>Related</th>
			
			<th colspan=3></th>


		</tr>

	</thead>
	<tbody>

			<% @courses.each do |course| %>
				<tr>
					<td><%= course.name %></td>
					<td><%= course.description.split[0...10].join(' ') %></td>
					<td><%= link_to "#{course.teacher.firstname} #{course.teacher.lastname}", teacher_path(course.teacher) %></td>
					<td> <% course.curriculum.each do |curriculum|  %>
						 <%= link_to curriculum.name, curriculum_path(curriculum) %>
						 <% end %>
					</td>
					<td><%= course.accademic_year.year %></td>
					<td>
						<%= link_to "Lectures",course_lectures_index_path(course)  %>
						<%= link_to "News",course_news_index_path(course) %>
						<%= link_to "Materials",course_material_index_path(course) %>

					</td>
					<td><%= link_to 'Show', course_path(course) %></td>
					<td><%= link_to 'Edit', course_edit_path(course) %></td>
					<td><%= link_to 'Destroy', course_path(course), method: :delete,data: { confirm: 'Are you sure?' }  %></td>

				</tr>

			<% end %>

	</tbody>


</table>

<%= will_paginate @courses %>

<%= render 'shared/hide_semantic_link' %>
<%= render 'shared/hide_structural_link' %>

app/views/course/new.html.erb
<%= title "New Course" %>

<%= render partial:'shared/error_partial', locals:{what: @course, name:'course'} %>
<%= render partial:'course_form', locals: {to_do:'create' , to_met: 'post', what: @course} %>


<%= render 'shared/hide_semantic_link' %>
<%= render 'shared/hide_structural_link' %>

app/views/course/syllabus.html.erb
<%= title "Program for #{@name}" %>
<p><%= @program %></p>

<%= render "shared/structural_link" %>
<%= render "shared/semantic_link" %>

app/views/course/timetable.html.erb
<%= title "Timetable for course #{@course.name}" %>


<table class="styled-table timetable" >
	<thead>
	<tr>
		<th colspan="1"></th>
		<% @weekday.each do |day| %>
			<th><%= day %></th>
		<% end %>
	</tr>
	</thead>
	<tbody>
		<% @rows.each do |row| %>
			<tr>
				<% row.each do |classroom| %>
				
					<% if classroom.is_a? Integer %>
						<td class="time"><%= "#{classroom}:00" %></td>
					<% elsif classroom.is_a? Hash %>
						<td class="classroom"><%= link_to classroom[:name], classroom_path(classroom[:id]) %></td>
					<% else %>
						<td></td>				
					<% end %>

				<% end %>

			</tr>
		<% end %>

		
		
	</tbody>

</table>


<%= render "shared/structural_link" %>
<%= render "shared/semantic_link" %>

app/views/course/view.html.erb
<%= render partial: 'show', locals: {course:@course} %>


<%= render "shared/structural_link" %>
<%= render "shared/semantic_link" %>

app/views/course/year_guided_tour.html.erb
<%= render partial: 'show', locals: {course: @courses.at(0)} %>


<div class="paginate">

<%= "Course <strong>#{@page}</strong> of <strong>#{@total_pages}</strong>".html_safe %>
<%= will_paginate @courses %>

</div>


<%= render 'shared/structural_link' %>
<%= render 'shared/semantic_link' %>