config/routes.rb
Rails.application.routes.draw do

  	devise_for :admins , controllers: { registrations: 'registration'}


	root to: "home#index"
	#Edit
	get 'home/edit' , to: 'home#edit', as: 'edit_home'
	patch 'home', to: 'home#update'


	# Landmarks
	get 'curricula' , to: 'curricula#view'			# Tutti i curriculum
	get 'courses' , to: 'courses#view'				# Tutti i corsi
	get 'services' , to: 'services#view'			# Tutti i servizi
	get 'services/type/:id/' , to: 'services#type'		# Servizi per tipo
	get 'contacts' , to: 'contacts#view', as: 'contact'			# Contatti
	get 'mission' , to: 'mission#view', as: 'mission'				# Mission & Principles
	get 'how_to_get_there' , to: 'how_to_get_there#view', as: 'how_to_get_there'	# Come arrivare
	get 'structures' , to: 'structures#view', as: 'structures'	# Tutte le strutture
	get 'structures/type/:id/' , to: 'structures#type'		# Strutture per tipo
	get 'events' , to: 'events#view'				# Tutti gli eventi
	post 'events/bydate' , to: 'events#bydate'			# Eventi per data
	get 'events/type/:id/' , to: 'events#type'			# Eventi per tipo
	get 'awards' , to: 'awards#view'				# Tutti i riconoscimenti
	get 'history', to: 'history#view', as: 'history'
	get 'alumni', to: 'alumni#view'


	#bureaucracy
	get 'bureaucracy' , to: 'bureaucracy#view', as: 'bureaucracy'	# Burocrazia
	get 'regulation' , to: 'regulation#view',as: 'regulation'	# Regolamento
	get 'costs' , to: 'costs#view', as: 'cost'	# Costi
	get 'bursary' , to: 'bursary#view', as: 'bursary'	# Borse di studio
	#Edit
	get 'bureaucracy/edit' , to: 'bureaucracy#edit', as: 'edit_bureaucracy'
	patch 'bureaucracy', to: 'bureaucracy#update'

	get 'regulation/edit' , to: 'regulation#edit', as: 'edit_regulation'
	patch 'regulation' , to: 'regulation#update'

	get 'costs/edit' , to: 'costs#edit', as: 'edit_cost'
	patch 'costs' , to: 'costs#update'

	get 'bursary/edit' , to: 'bursary#edit', as: 'edit_bursary'
	patch 'bursary' , to: 'bursary#update'

	#Edit for single topic

	get 'mission/edit' , to: 'mission#edit', as: 'edit_mission'
	patch 'mission', to: 'mission#update'

	get 'history/edit' , to: 'history#edit', as: 'edit_history'
	patch 'history', to: 'history#update'

	get 'awards/edit' , to: 'awards#edit', as: 'edit_awards'
	patch 'awards', to: 'awards#update'

	get 'how_to_get_there/edit' , to: 'how_to_get_there#edit', as: 'edit_how_to_get_there'
	patch 'how_to_get_there', to: 'how_to_get_there#update'

	get 'contacts/edit' , to: 'contacts#edit', as: 'edit_contacts'
	patch 'contacts', to: 'contacts#update'

	# CRUD Course pages
	get 'courses/index', to: 'course#index', as: 'course_index'
	get 'courses/new', to: 'course#new', as: 'new_course'
	post 'courses', to: 'course#create'
	get 'course/:id', to: 'course#view', as: 'course'
	get 'course/:id/edit', to: 'course#edit', as: 'course_edit'
	put 'course/:id', to: 'course#update'
	delete 'course/:id', to: 'course#destroy'



	#Courses page
	get 'course/:id/syllabus' , to: 'course#syllabus', as: 'course_syllabus'
	get 'course/:id/timetable' , to: 'course#timetable', as: 'course_timetable'
	get 'course/:id/materials' , to: 'course#materials', as: 'course_materials'
	get 'course/:id/exams' , to: 'course#exams', as: 'course_exams'
	get 'course/:id/curricula' , to: 'course#curricula', as: 'course_curricula'

	#Dirty way for gt!
	get 'courses/courses_by_type/:curriculum_id/:id/syllabus' , to: 'course#syllabus', as: 'courses_type_guided_tour_id_syllabus'
	get 'courses/courses_by_year/:courses_year/:id/syllabus' , to: 'course#syllabus', as: 'courses_year_guided_tour_id_syllabus'
	get 'courses/courses_by_type/:curriculum_id/:id/timetable' , to: 'course#timetable', as: 'courses_type_guided_tour_id_timetable'
	get 'courses/courses_by_year/:courses_year/:id/timetable' , to: 'course#timetable', as: 'courses_year_guided_tour_id_timetable'




	#CRUD courses news
	get 'course/:course_id/news/index' , to: 'news#index', as: 'course_news_index'
	get 'course/:course_id/news/new' , to: 'news#new', as: 'new_course_news'
	post 'course/:course_id/news' , to: 'news#create'
	get 'course/:course_id/news/:id/edit' , to: 'news#edit', as: 'edit_course_new'
	put 'course/:course_id/news/:id' , to: 'news#update'
	delete 'course/:course_id/news/:id' , to: 'news#destroy'
	# News pages
	get 'course/:course_id/news/:id' , to: 'news#view', as: 'course_new'


	#Courses news
	get 'course/:id/news' , to: 'news#news', as: 'course_news'
	delete 'course/:course_id/news/:id' , to: 'news#destroy'

	#Lecture CRUD
	get 'course/:course_id/lectures/index' , to: 'lectures#index', as: 'course_lectures_index'
	get 'course/:course_id/lectures/new' , to: 'lectures#new', as: 'new_course_lecture'
	post 'course/:course_id/lectures' , to: 'lectures#create'
	get  'course/:course_id/lectures/:id/edit' , to: 'lectures#edit', as: 'edit_course_lecture'
	put  'course/:course_id/lectures/:id' , to: 'lectures#update', as: 'update_course_lecture'
	delete 'course/:course_id/lectures/:id' , to: 'lectures#destroy'

	#lecture pages
	get 'course/:course_id/lectures/:id' , to: 'lectures#show', as: 'course_lecture'

	#courses pages
	get 'courses/courses_by_year' , to: 'course#courses_by_year', as: 'courses_by_year'
	get 'courses/courses_by_type' , to: 'course#courses_by_type', as: 'courses_by_type'
	post 'courses/courses_by_year' , to: 'course#courses_by_year'
	post 'courses/courses_by_type' , to: 'course#courses_by_type'
	get 'courses/courses_by_type/:id' , to: 'course#type_guided_tour', as: 'courses_type_guided_tour'
	get 'courses/courses_by_year/:id' , to: 'course#year_guided_tour', as: 'courses_year_guided_tour'
	get 'courses/courses_by_type/:curriculum_id/:id' , to: 'course#type_guided_tour', as: 'courses_type_guided_tour_id'
	get 'courses/courses_by_year/:courses_year/:id' , to: 'course#year_guided_tour', as: 'courses_year_guided_tour_id'


	# Teacher pages
  get 'teacher/index' , to: 'teacher#index', as: 'teacher_index'
	get 'teacher/new' , to: 'teacher#new', as: 'new_teacher'
	get 'teacher/:id' , to: 'teacher#view', as: 'teacher'
	get 'teacher/:id/curriculum' , to: 'teacher#curriculum', as: 'teacher_curriculum'

	#CRUD teacher

	post 'teacher' , to: 'teacher#create'
	get 'teacher/:id/edit' , to: 'teacher#edit', as: 'edit_teacher'
	put 'teacher/:id' , to: 'teacher#update'
	delete 'teacher/:id' , to: 'teacher#destroy'

	# Curriculum new, edit, and destoy
	get 'curriculum/index' , to: 'curriculum#index', as: 'curriculum_index'
	get 'curriculum/new' , to: 'curriculum#new', as: 'new_curriculum'
	get 'curriculum/:curriculum_id/courses/index', to: 'curriculum#manage_courses', as: 'curriculum_courses'
	get 'curriculum/:curriculum_id/courses/list', to: 'curriculum#list_courses_to_add', as: 'list_curriculum_courses'
	put 'curriculum/:curriculum_id/courses/:id', to: 'curriculum#add_course', as: 'add_curriculum_course'
	delete 'curriculum/:curriculum_id/courses/:id', to: 'curriculum#remove_course'
	post 'curriculum' , to: 'curriculum#create'
	get 'curriculum/:id/edit' , to: 'curriculum#edit', as: 'edit_curriculum'
	put 'curriculum/:id' , to: 'curriculum#update'
	delete 'curriculum/:id' , to: 'curriculum#destroy'

	# Curriculum pages
	get 'curriculum/:id' , to: 'curriculum#view', as: 'curriculum_id'
	get 'curriculum/:id/work_opportunity' , to: 'curriculum#work_opportunity', as: 'curriculum_work_opportunity'



	#CRUD Material
	get 'course/:course_id/material/index' , to: 'material#index', as: 'course_material_index'
	get 'course/:course_id/material/new' , to: 'material#new', as: 'new_course_material'
	post 'course/:course_id/material' , to: 'material#create'
	get  'course/:course_id/material/:id/edit' , to: 'material#edit', as: 'edit_course_material'
	put  'course/:course_id/material/:id' , to: 'material#update', as: 'update_course_material'
	delete 'course/:course_id/material/:id' , to: 'material#destroy'
	# Material pages
	get 'course/:course_id/material/:id' , to: 'material#view', as: 'material'

	# Exams pages
  	get 'exam/index' , to: 'exam#index', as: 'exam_index'
	get 'exam/new' , to: 'exam#new', as: 'new_exam'
	get 'exam/:id' , to: 'exam#view', as: 'exam'

	# CRUD exam

	post 'exam' , to: 'exam#create'
	get 'exam/:id/edit' , to: 'exam#edit', as: 'edit_exam'
	put 'exam/:id' , to: 'exam#update'
	delete 'exam/:id' , to: 'exam#destroy'

	# Classrooms pages
	get 'classroom/new' , to: 'classroom#new', as: 'new_classroom'
  get 'classroom/index', to: 'classroom#index', as: 'classroom_index'
	get 'classroom/:id' , to: 'classroom#view' , as: 'classroom'
	get 'classroom/:id/how_to_get_there' , to: 'classroom#how_to_get_there', as: "classroom_htgt"
	get 'classroom/:id/services', to: 'classroom#services', as: 'classroom_services'
	get 'classroom/:id/exams', to: 'classroom#exams', as: 'classroom_exams'
	get 'classroom/:id/courses', to: 'classroom#courses', as: 'classroom_courses'

	#CRUD classroom

	post 'classroom' , to: 'classroom#create'
	get 'classroom/:id/edit' , to: 'classroom#edit', as: 'edit_classroom'
	put 'classroom/:id' , to: 'classroom#update'
	delete 'classroom/:id' , to: 'classroom#destroy'

	# Student's services pages
	get 'service/index' , to: 'service#index', as: 'service_index'
	get 'service/:id' , to: 'service#view', as: 'service'
	get 'service/:id/reference' , to: 'service#reference', as: 'service_reference'
	# CRUD services
	get 'services/new' , to: 'service#new', as: 'new_service'
	post 'service' , to: 'service#create'
	get 'service/:id/edit' , to: 'service#edit', as: 'edit_service'
	put 'service/:id' , to: 'service#update'
	delete 'service/:id' , to: 'service#destroy'

	# Structures pages
	get 'structure/index', to: 'structure#index', as: 'structure_index'
	get 'structure/:id' , to: 'structure#view', as: 'structure'
	get 'structure/:id/map' , to: 'structure#map', as: 'structure_map'
	get 'structure/:id/photogallery' , to: 'structure#photogallery', as: 'structure_photos'
	get 'structure/:id/events' , to: 'structure#events', as: 'structure_events'
	get 'structure/:id/services' , to: 'structure#services', as: 'structure_services'
	#CRUD structures

app/views/shared/_admin_menu.html.erb
<!-- apply different class to the admin menu to make if longer when admin is logged in -->
<div id='admin_menu' class="<%=  admin_signed_in? ? 'signed_in' : 'signed_out' %>">
	
	<% if admin_signed_in? %>

		<ul class="sf-menu">
			<li><%= link_to "Admin Menu:", '', { class: "no-link" } %>		
				<ul>
					<li><%= link_to "Edit admin data",edit_admin_registration_path %></li>
					<li><%= link_to "Sign out", destroy_admin_session_path %></li>
				</ul>
			</li>

			<li><%= link_to 'Single pages', '#' %>
				<ul>
					<li><%= link_to 'Edit Homepage', edit_home_path %></li>
					<li><%= link_to 'Edit mission', edit_mission_path %></li>
					<li><%= link_to 'Edit history', edit_history_path %></li>
					<li><%= link_to 'Edit reach us', edit_how_to_get_there_path %></li>
					<li><%= link_to 'Edit contacts',edit_contacts_path %></li>
					<li><%=  %></li>
				</ul>
			</li>

			<li><%= link_to 'Bureaucracy', '#' %>
				<ul>
					<li><%= link_to 'Edit Bureaucracy', edit_bureaucracy_path %></li>
					<li><%= link_to 'Edit Regulation',edit_regulation_path %></li>
					<li><%= link_to 'Edit Costs',edit_cost_path %></li>
					<li><%= link_to 'Edit Bursary', edit_bursary_path %></li>
				</ul>
			</li>

			<li><%= link_to "Courses", course_index_path %>
				<ul>
					<li><%= link_to "New course", new_course_path %></li>
					<li><%= link_to "All courses", course_index_path  %></li>
				</ul>
			</li>
			
			<li><%= link_to "Curricula", curriculum_index_path %>
				<ul>
					<li><%= link_to "New curriculum", new_curriculum_path%></li></li>
					<li><%= link_to "All curricula", curriculum_index_path%></li>

				</ul>
			</li>

			<li><%= link_to "Services",service_index_path %>
				<ul>
					<li><%= link_to "New service", new_service_path %></li>
					<li><%= link_to "All services", service_index_path %></li>
				</ul>
			</li>

			<li ><%= link_to "Structures", structure_index_path %>
				<ul>
					<li><%= link_to "New structure", new_structure_path %></li>
					<li><%= link_to "All structures", structure_index_path %></li>
				</ul>
			</li>

			<li ><%= link_to "Events", event_index_path %>
				<ul>
					<li><%= link_to "New event", new_event_path %></li>
					<li><%= link_to "All events", event_index_path %></li>
				</ul>
			</li>

			<li><%= link_to "Teachers", teacher_index_path %>
				<ul>
					<li><%= link_to 'New teacher', new_teacher_path %></li>
					<li><%= link_to "All Teachers", teacher_index_path %></li>
				</ul>
			</li>

			<li><%= link_to "Exams", exam_index_path %>
				<ul>
					<li><%= link_to 'New exam', new_exam_path %></li>
					<li><%= link_to 'All Exams', exam_index_path %></li>
				</ul>
			</li>

			<li><%= link_to 'Classroom', classroom_index_path %>
				<ul>
					<li><%= link_to 'New Classroom', new_classroom_path %></li>
					<li><%= link_to 'All Classrooms', classroom_index_path %></li>
				</ul>
			</li>
			<li><%= link_to 'Awards', awards_index_path %>
				<ul>
					<li><%= link_to 'New Award', new_award_path %></li>
					<li><%= link_to 'All Awards', awards_index_path %></li>
				</ul>
			</li>
		</ul>
	<% else %>

		<ul class="landmark-menu login">
			<li><%= link_to 'Login',new_admin_session_path  %></li>
		</ul>

	
	<% end %>
</div>

app/views/shared/_course_type_form.html.erb
<% curriculums=@curriculum.map { |c| [c.name, c.id] } %>

<%= form_for :curriculums, url: { controller: 'course', action: "courses_by_type" } do |f| %>
<%= f.label "Search for course's type" %>
<%= f.select(:type, options_for_select(curriculums)) %>
<%= f.hidden_field  :gt, value: "type"%>
<%= f.submit :search %>
<% end %>

app/views/shared/_course_year_form.html.erb
<% years=@courses_year.map { |year| [year, year] } %>

<%= form_for :course, url: { controller: 'course', action: "courses_by_year" } do |f| %>
<%= f.label "Search for course's year" %>
<%= f.select(:year, options_for_select(years)) %>
	<%= f.submit :search %>
<% end %>
	

app/views/shared/_curriculum_table.html.erb
<table class="styled-table" >
	<thead>
		<th>Curriculum</th>
		<th>Description</th>
		
	</tr>
	</thead>
	<tbody>
		<% @curricula.each do |curriculum| %>
	  	
			<tr>
				<td><%= link_to curriculum.name, curriculum_id_path(curriculum) %></td>
				<td><%= curriculum.description.split[0...Course.max_word].join(' ') %></td>

			</tr>
	  	
		<% end %>
		
	</tbody>

</table>	

app/views/shared/_error_partial.html.erb
<% if what.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(what.errors.count, "error") %> prohibited
			this <%= name %> from being saved:</h2>
		<ul>
			<% what.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_footer_menu.html.erb
<ul class=landmark-footer-menu>
	    <li ><a href="/bureaucracy">Bureaucracy</a></li>
	    <li ><a href="/mission">Mission</a></li>
	    <li ><a href="/history">History</a></li>
	    <li ><a href="/awards">Awards</a></li>
	    <li ><a href="/how_to_get_there">How to reach</a></li>
	    <li ><a href="/contacts">Contacts</a></li>
</ul>

app/views/shared/_form_for_curriculum.html.erb
<%= form_for @curriculum do |f| %>
	<p>
		<%= f.label :name %> <br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :description %> <br>
		<%= f.text_area :description %>

	</p>
	<p>
		<%= f.label :work_opportunity %> <br>
		<%= f.text_area :work_opportunity %>
		
	</p>

	<p>
    	<%= f.submit %>
  	</p>

<% end %>

app/views/shared/_hide_semantic_link.html.erb
<style type="text/css">  
	#semantic-block{
		
		display:none !important;
		
	}
</style>  

app/views/shared/_hide_structural_link.html.erb
<style type="text/css">  
	#structural-block{
		
		display:none !important;
		
	}
</style>  

app/views/shared/_landmark_menu.html.erb
<ul class=landmark-menu>
    <li ><%= link_to "Home", root_path %></li>
    <li ><%= link_to "Courses", courses_path %></li>
    <li ><%= link_to "Curricula", curricula_path %></li>
    <li ><%= link_to "Services", services_path %></li>
    <li ><%= link_to "Structures", structures_path %></li>
    <li ><%= link_to "Events", events_path %></li>
</ul>

app/views/shared/_semantic_link.html.erb
<% content_for :semanticLinkMenu do%>
	<ul class=menu>
	
		<% if @semant_links
			@semant_links.each do |element| %>
			  <li><a href="<%= element[:value] %>"><%= element[:name] %></a></li>
			<%end %>
					
		<%end%>
	</ul>

<% end %>

app/views/shared/_structural_link.html.erb
<% content_for :structuralLinkMenu do%>
	<ul class=menu>
		<% 	if @struct_links
			@struct_links.each do |element| %>
				<li><%= link_to element[:name], element[:value] %></a></li>
			<% end %>

		<% end %>
	</ul>
<% end %>